name: Destroy Development environment

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Terraform init
        working-directory: environments/development
        run: terraform init

      - name: Terraform destroy
        working-directory: environments/development
        run: terraform destroy -var="access_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve
