name: Build ECS and create cluster service - Dev environment

on:
  push:
    branches: [dev]
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  plan:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var-file="env/dev.tfvars"

      - name: Terraform apply
        run: terraform apply -var-file="env/dev.tfvars" -auto-approve
